<script setup lang="ts">
import { computed } from 'vue'
import {
  Radar,
  Boxes,
  ShieldAlert,
  KeyRound,
  Crosshair,
  Network,
  RadioTower,
  Terminal,
  Cloud,
  Wrench,
  Microscope,
  Search,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  ArrowUp,
  ArrowDown,
  Plus,
  X,
  Settings,
  ListChecks,
  Bell,
  PanelLeftClose,
  PanelLeftOpen,
  Folder,
  Globe,
  Monitor,
  Download,
  Upload,
  RotateCcw,
  Trash2,
  Check,
  Info,
  CircleAlert,
  CircleDashed,
  ArrowUpRight,
  SlidersHorizontal,
  Layers,
  GripVertical,
  Ellipsis,
  FileText,
  Play,
  RefreshCw,
  ShieldCheck,
  FolderOpen,
  CircleHelp,
} from '@lucide/vue'
const props = withDefaults(defineProps<{ name: string; size?: number }>(), { size: 18 })
const icons: Record<string, typeof Radar> = {
  radar: Radar,
  boxes: Boxes,
  'shield-alert': ShieldAlert,
  'key-round': KeyRound,
  crosshair: Crosshair,
  network: Network,
  'radio-tower': RadioTower,
  terminal: Terminal,
  cloud: Cloud,
  wrench: Wrench,
  microscope: Microscope,
  search: Search,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  plus: Plus,
  x: X,
  settings: Settings,
  tasks: ListChecks,
  bell: Bell,
  collapse: PanelLeftClose,
  expand: PanelLeftOpen,
  folder: Folder,
  globe: Globe,
  monitor: Monitor,
  download: Download,
  upload: Upload,
  reset: RotateCcw,
  trash: Trash2,
  check: Check,
  info: Info,
  alert: CircleAlert,
  loading: CircleDashed,
  external: ArrowUpRight,
  sliders: SlidersHorizontal,
  layers: Layers,
  grip: GripVertical,
  more: Ellipsis,
  file: FileText,
  play: Play,
  refresh: RefreshCw,
  shield: ShieldCheck,
  'folder-open': FolderOpen,
}
const icon = computed(() => icons[props.name] ?? CircleHelp)
</script>
<template>
  <component :is="icon" :size="size" :stroke-width="1.7" aria-hidden="true" class="ui-icon" />
</template>
