import type { Layout } from '../storage/layout'

export interface FeatureRegistration {
  id: string
  nameKey: string
  descriptionKey: string
  icon: string
  route: string
  status: 'designing' | 'planned'
  tags: string[]
}

export const features: FeatureRegistration[] = [
  {
    id: 'portscan',
    nameKey: 'screen.portscan.title',
    descriptionKey: 'screen.portscan.description',
    icon: 'radar',
    route: '/recon/portscan',
    status: 'designing',
    tags: ['network', 'host'],
  },
  {
    id: 'service-identification',
    nameKey: 'screen.service-identification.title',
    descriptionKey: 'screen.service-identification.description',
    icon: 'radar',
    route: '/recon/service-identification',
    status: 'planned',
    tags: ['network', 'host'],
  },
  {
    id: 'subdomain',
    nameKey: 'screen.subdomain.title',
    descriptionKey: 'screen.subdomain.description',
    icon: 'radar',
    route: '/recon/subdomain',
    status: 'planned',
    tags: ['network', 'host'],
  },
  {
    id: 'dns-whois',
    nameKey: 'screen.dns-whois.title',
    descriptionKey: 'screen.dns-whois.description',
    icon: 'radar',
    route: '/recon/dns-whois',
    status: 'planned',
    tags: ['network', 'host'],
  },
  {
    id: 'liveness',
    nameKey: 'screen.liveness.title',
    descriptionKey: 'screen.liveness.description',
    icon: 'radar',
    route: '/recon/liveness',
    status: 'planned',
    tags: ['network', 'host'],
  },
  {
    id: 'osint',
    nameKey: 'screen.osint.title',
    descriptionKey: 'screen.osint.description',
    icon: 'radar',
    route: '/recon/osint',
    status: 'planned',
    tags: ['network', 'host'],
  },
  {
    id: 'web-fingerprint',
    nameKey: 'screen.web-fingerprint.title',
    descriptionKey: 'screen.web-fingerprint.description',
    icon: 'boxes',
    route: '/asset/web-fingerprint',
    status: 'planned',
    tags: [],
  },
  {
    id: 'component-fingerprint',
    nameKey: 'screen.component-fingerprint.title',
    descriptionKey: 'screen.component-fingerprint.description',
    icon: 'boxes',
    route: '/asset/component-fingerprint',
    status: 'planned',
    tags: [],
  },
  {
    id: 'cms-identification',
    nameKey: 'screen.cms-identification.title',
    descriptionKey: 'screen.cms-identification.description',
    icon: 'boxes',
    route: '/asset/cms-identification',
    status: 'planned',
    tags: [],
  },
  {
    id: 'asset-dedup',
    nameKey: 'screen.asset-dedup.title',
    descriptionKey: 'screen.asset-dedup.description',
    icon: 'boxes',
    route: '/asset/asset-dedup',
    status: 'planned',
    tags: [],
  },
  {
    id: 'poc-scan',
    nameKey: 'screen.poc-scan.title',
    descriptionKey: 'screen.poc-scan.description',
    icon: 'shield-alert',
    route: '/vuln/poc-scan',
    status: 'planned',
    tags: [],
  },
  {
    id: 'nuclei',
    nameKey: 'screen.nuclei.title',
    descriptionKey: 'screen.nuclei.description',
    icon: 'shield-alert',
    route: '/vuln/nuclei',
    status: 'planned',
    tags: [],
  },
  {
    id: 'afrog',
    nameKey: 'screen.afrog.title',
    descriptionKey: 'screen.afrog.description',
    icon: 'shield-alert',
    route: '/vuln/afrog',
    status: 'planned',
    tags: [],
  },
  {
    id: 'xray',
    nameKey: 'screen.xray.title',
    descriptionKey: 'screen.xray.description',
    icon: 'shield-alert',
    route: '/vuln/xray',
    status: 'planned',
    tags: [],
  },
  {
    id: 'directory-scan',
    nameKey: 'screen.directory-scan.title',
    descriptionKey: 'screen.directory-scan.description',
    icon: 'shield-alert',
    route: '/vuln/directory-scan',
    status: 'planned',
    tags: [],
  },
  {
    id: 'access-control-check',
    nameKey: 'screen.access-control-check.title',
    descriptionKey: 'screen.access-control-check.description',
    icon: 'shield-alert',
    route: '/vuln/access-control-check',
    status: 'planned',
    tags: [],
  },
  {
    id: 'weak-credential',
    nameKey: 'screen.weak-credential.title',
    descriptionKey: 'screen.weak-credential.description',
    icon: 'key-round',
    route: '/auth/weak-credential',
    status: 'planned',
    tags: [],
  },
  {
    id: 'hash-analysis',
    nameKey: 'screen.hash-analysis.title',
    descriptionKey: 'screen.hash-analysis.description',
    icon: 'key-round',
    route: '/auth/hash-analysis',
    status: 'planned',
    tags: [],
  },
  {
    id: 'kerberos-audit',
    nameKey: 'screen.kerberos-audit.title',
    descriptionKey: 'screen.kerberos-audit.description',
    icon: 'key-round',
    route: '/auth/kerberos-audit',
    status: 'planned',
    tags: [],
  },
  {
    id: 'jwt-session',
    nameKey: 'screen.jwt-session.title',
    descriptionKey: 'screen.jwt-session.description',
    icon: 'key-round',
    route: '/auth/jwt-session',
    status: 'planned',
    tags: [],
  },
  {
    id: 'exploit-connector',
    nameKey: 'screen.exploit-connector.title',
    descriptionKey: 'screen.exploit-connector.description',
    icon: 'crosshair',
    route: '/exploit/exploit-connector',
    status: 'planned',
    tags: [],
  },
  {
    id: 'web-validation',
    nameKey: 'screen.web-validation.title',
    descriptionKey: 'screen.web-validation.description',
    icon: 'crosshair',
    route: '/exploit/web-validation',
    status: 'planned',
    tags: [],
  },
  {
    id: 'local-privesc',
    nameKey: 'screen.local-privesc.title',
    descriptionKey: 'screen.local-privesc.description',
    icon: 'crosshair',
    route: '/exploit/local-privesc',
    status: 'planned',
    tags: [],
  },
  {
    id: 'container-escape',
    nameKey: 'screen.container-escape.title',
    descriptionKey: 'screen.container-escape.description',
    icon: 'crosshair',
    route: '/exploit/container-escape',
    status: 'planned',
    tags: [],
  },
  {
    id: 'internal-scan',
    nameKey: 'screen.internal-scan.title',
    descriptionKey: 'screen.internal-scan.description',
    icon: 'network',
    route: '/post/internal-scan',
    status: 'planned',
    tags: [],
  },
  {
    id: 'lateral-assessment',
    nameKey: 'screen.lateral-assessment.title',
    descriptionKey: 'screen.lateral-assessment.description',
    icon: 'network',
    route: '/post/lateral-assessment',
    status: 'planned',
    tags: [],
  },
  {
    id: 'ad-assessment',
    nameKey: 'screen.ad-assessment.title',
    descriptionKey: 'screen.ad-assessment.description',
    icon: 'network',
    route: '/post/ad-assessment',
    status: 'planned',
    tags: [],
  },
  {
    id: 'credential-risk',
    nameKey: 'screen.credential-risk.title',
    descriptionKey: 'screen.credential-risk.description',
    icon: 'network',
    route: '/post/credential-risk',
    status: 'planned',
    tags: [],
  },
  {
    id: 'c2-connector',
    nameKey: 'screen.c2-connector.title',
    descriptionKey: 'screen.c2-connector.description',
    icon: 'radio-tower',
    route: '/c2/c2-connector',
    status: 'planned',
    tags: [],
  },
  {
    id: 'agent-state',
    nameKey: 'screen.agent-state.title',
    descriptionKey: 'screen.agent-state.description',
    icon: 'radio-tower',
    route: '/c2/agent-state',
    status: 'planned',
    tags: [],
  },
  {
    id: 'channel-state',
    nameKey: 'screen.channel-state.title',
    descriptionKey: 'screen.channel-state.description',
    icon: 'radio-tower',
    route: '/c2/channel-state',
    status: 'planned',
    tags: [],
  },
  {
    id: 'persistence-review',
    nameKey: 'screen.persistence-review.title',
    descriptionKey: 'screen.persistence-review.description',
    icon: 'radio-tower',
    route: '/c2/persistence-review',
    status: 'planned',
    tags: [],
  },
  {
    id: 'webshell-connector',
    nameKey: 'screen.webshell-connector.title',
    descriptionKey: 'screen.webshell-connector.description',
    icon: 'terminal',
    route: '/webshell/webshell-connector',
    status: 'planned',
    tags: [],
  },
  {
    id: 'session-terminal',
    nameKey: 'screen.session-terminal.title',
    descriptionKey: 'screen.session-terminal.description',
    icon: 'terminal',
    route: '/webshell/session-terminal',
    status: 'planned',
    tags: [],
  },
  {
    id: 'session-files',
    nameKey: 'screen.session-files.title',
    descriptionKey: 'screen.session-files.description',
    icon: 'terminal',
    route: '/webshell/session-files',
    status: 'planned',
    tags: [],
  },
  {
    id: 'cloud-discovery',
    nameKey: 'screen.cloud-discovery.title',
    descriptionKey: 'screen.cloud-discovery.description',
    icon: 'cloud',
    route: '/cloud/cloud-discovery',
    status: 'planned',
    tags: [],
  },
  {
    id: 'credential-leak',
    nameKey: 'screen.credential-leak.title',
    descriptionKey: 'screen.credential-leak.description',
    icon: 'cloud',
    route: '/cloud/credential-leak',
    status: 'planned',
    tags: [],
  },
  {
    id: 'cloud-audit',
    nameKey: 'screen.cloud-audit.title',
    descriptionKey: 'screen.cloud-audit.description',
    icon: 'cloud',
    route: '/cloud/cloud-audit',
    status: 'planned',
    tags: [],
  },
  {
    id: 'k8s-security',
    nameKey: 'screen.k8s-security.title',
    descriptionKey: 'screen.k8s-security.description',
    icon: 'cloud',
    route: '/cloud/k8s-security',
    status: 'planned',
    tags: [],
  },
  {
    id: 'codec',
    nameKey: 'screen.codec.title',
    descriptionKey: 'screen.codec.description',
    icon: 'wrench',
    route: '/toolbox/codec',
    status: 'planned',
    tags: [],
  },
  {
    id: 'crypto',
    nameKey: 'screen.crypto.title',
    descriptionKey: 'screen.crypto.description',
    icon: 'wrench',
    route: '/toolbox/crypto',
    status: 'planned',
    tags: [],
  },
  {
    id: 'guomi',
    nameKey: 'screen.guomi.title',
    descriptionKey: 'screen.guomi.description',
    icon: 'wrench',
    route: '/toolbox/guomi',
    status: 'planned',
    tags: [],
  },
  {
    id: 'hash-jwt',
    nameKey: 'screen.hash-jwt.title',
    descriptionKey: 'screen.hash-jwt.description',
    icon: 'wrench',
    route: '/toolbox/hash-jwt',
    status: 'planned',
    tags: [],
  },
  {
    id: 'format-convert',
    nameKey: 'screen.format-convert.title',
    descriptionKey: 'screen.format-convert.description',
    icon: 'wrench',
    route: '/toolbox/format-convert',
    status: 'planned',
    tags: [],
  },
  {
    id: 'proxy-tunnel',
    nameKey: 'screen.proxy-tunnel.title',
    descriptionKey: 'screen.proxy-tunnel.description',
    icon: 'wrench',
    route: '/toolbox/proxy-tunnel',
    status: 'planned',
    tags: [],
  },
  {
    id: 'text-tools',
    nameKey: 'screen.text-tools.title',
    descriptionKey: 'screen.text-tools.description',
    icon: 'wrench',
    route: '/toolbox/text-tools',
    status: 'planned',
    tags: [],
  },
  {
    id: 'log-analysis',
    nameKey: 'screen.log-analysis.title',
    descriptionKey: 'screen.log-analysis.description',
    icon: 'microscope',
    route: '/forensics/log-analysis',
    status: 'planned',
    tags: [],
  },
  {
    id: 'memory-forensics',
    nameKey: 'screen.memory-forensics.title',
    descriptionKey: 'screen.memory-forensics.description',
    icon: 'microscope',
    route: '/forensics/memory-forensics',
    status: 'planned',
    tags: [],
  },
  {
    id: 'pcap-analysis',
    nameKey: 'screen.pcap-analysis.title',
    descriptionKey: 'screen.pcap-analysis.description',
    icon: 'microscope',
    route: '/forensics/pcap-analysis',
    status: 'planned',
    tags: [],
  },
  {
    id: 'incident-response',
    nameKey: 'screen.incident-response.title',
    descriptionKey: 'screen.incident-response.description',
    icon: 'microscope',
    route: '/forensics/incident-response',
    status: 'planned',
    tags: [],
  },
  {
    id: 'ioc-query',
    nameKey: 'screen.ioc-query.title',
    descriptionKey: 'screen.ioc-query.description',
    icon: 'radar',
    route: '/intel/ioc-query',
    status: 'planned',
    tags: [],
  },
  {
    id: 'intel-aggregation',
    nameKey: 'screen.intel-aggregation.title',
    descriptionKey: 'screen.intel-aggregation.description',
    icon: 'radar',
    route: '/intel/intel-aggregation',
    status: 'planned',
    tags: [],
  },
]

export const featureById = new Map(features.map((feature) => [feature.id, feature]))

export const defaultLayout: Layout = {
  version: 1,
  layoutId: 'default',
  groups: [
    {
      id: 'recon',
      name: 'nav.group.recon',
      icon: 'radar',
      items: ['portscan', 'service-identification', 'subdomain', 'dns-whois', 'liveness', 'osint'],
    },
    {
      id: 'asset',
      name: 'nav.group.asset',
      icon: 'boxes',
      items: ['web-fingerprint', 'component-fingerprint', 'cms-identification', 'asset-dedup'],
    },
    {
      id: 'vuln',
      name: 'nav.group.vuln',
      icon: 'shield-alert',
      items: ['poc-scan', 'nuclei', 'afrog', 'xray', 'directory-scan', 'access-control-check'],
    },
    {
      id: 'auth',
      name: 'nav.group.auth',
      icon: 'key-round',
      items: ['weak-credential', 'hash-analysis', 'kerberos-audit', 'jwt-session'],
    },
    {
      id: 'exploit',
      name: 'nav.group.exploit',
      icon: 'crosshair',
      items: ['exploit-connector', 'web-validation', 'local-privesc', 'container-escape'],
    },
    {
      id: 'post',
      name: 'nav.group.post',
      icon: 'network',
      items: ['internal-scan', 'lateral-assessment', 'ad-assessment', 'credential-risk'],
    },
    {
      id: 'c2',
      name: 'nav.group.c2',
      icon: 'radio-tower',
      items: ['c2-connector', 'agent-state', 'channel-state', 'persistence-review'],
    },
    {
      id: 'webshell',
      name: 'nav.group.webshell',
      icon: 'terminal',
      items: ['webshell-connector', 'session-terminal', 'session-files'],
    },
    {
      id: 'cloud',
      name: 'nav.group.cloud',
      icon: 'cloud',
      items: ['cloud-discovery', 'credential-leak', 'cloud-audit', 'k8s-security'],
    },
    {
      id: 'toolbox',
      name: 'nav.group.toolbox',
      icon: 'wrench',
      items: ['codec', 'crypto', 'guomi', 'hash-jwt', 'format-convert', 'proxy-tunnel', 'text-tools'],
    },
    {
      id: 'forensics',
      name: 'nav.group.forensics',
      icon: 'microscope',
      items: ['log-analysis', 'memory-forensics', 'pcap-analysis', 'incident-response'],
    },
    {
      id: 'intel',
      name: 'nav.group.intel',
      icon: 'radar',
      items: ['ioc-query', 'intel-aggregation'],
    },
  ],
  hidden: [],
}
